#!/bin/bash

echo "🔧 Setting up CloudId for Atlassian MCP Tools"
echo "============================================"

echo ""
echo "The system now uses the ATLASSIAN_CLOUD_ID environment variable for automatic cloudId injection."
echo ""
echo "You can find your cloudId by:"
echo "1. Going to your Atlassian instance (e.g., https://your-domain.atlassian.net)"
echo "2. Looking at the URL - it should contain your cloudId"
echo "3. Or check your Atlassian admin settings"
echo ""
echo "Set the environment variable in one of these ways:"
echo ""
echo "Option 1 - Export for current session:"
echo "export ATLASSIAN_CLOUD_ID=\"your-actual-cloud-id\""
echo ""
echo "Option 2 - Add to your shell profile (~/.zshrc, ~/.bashrc, etc.):"
echo "echo 'export ATLASSIAN_CLOUD_ID=\"your-actual-cloud-id\"' >> ~/.zshrc"
echo "source ~/.zshrc"
echo ""
echo "Option 3 - Set it when running the command:"
echo "ATLASSIAN_CLOUD_ID=\"your-actual-cloud-id\" npm run ai"
echo ""
echo "Example:"
echo "export ATLASSIAN_CLOUD_ID=\"12345678-1234-1234-1234-123456789012\""
echo ""
echo "After setting the environment variable, restart your AI CLI with: npm run ai" 